"""PAPI-90 item 1: the code-owned strict sandbox policy for a Claude agent lane.

Every test here is about something a lane could do before this policy existed
and cannot express now: read the operator's home through an absolute path, write
outside its worktree, reach a domain, reach another lane's socket, or use one of
the model client's own file tools, which are not subject to the Bash sandbox at
all.

The settings file is generated by the launcher, per launch, and re-read from
disk and proved again immediately before the spawn. A run configuration cannot
supply one, replace one, or add a settings *source* beside one.
"""
from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from _support import (
    HEAD_A,
    lane_bin,
    make_broker,
    make_config,
    make_source_repo,
    parent_env,
)

from pr_prover.childenv import CAPABILITY_SECRET, SUBPROCESS_ENV_SCRUB
from pr_prover.commands import CommandResult
from pr_prover.errors import LaunchPolicyError
from pr_prover.launchers import (
    FORBIDDEN_FLAGS,
    SETTING_SOURCES_ENTRY,
    AgentSpec,
    BoundContext,
    assert_launchable,
)
from pr_prover.sandbox import (
    CREDENTIAL_HOME_SUBPATHS,
    ENV_SCRUB_VALUE,
    IGNORED_SANDBOX_KEYS,
    KNOWN_FILESYSTEM_KEYS,
    KNOWN_NETWORK_KEYS,
    KNOWN_SANDBOX_KEYS,
    OUTSIDE_SANDBOX_TOOLS,
    REQUIRED,
    SANDBOXED_TOOLS,
    assert_settings,
    decides,
    document,
    read_and_assert,
    write,
)

BOUND = BoundContext(repo="example/repo", pr=7, branch="feat/example", base="main", head=HEAD_A)
AGENT = AgentSpec(program="claude", model="opus", tools=("Bash", "TodoWrite"))

# One lane, laid out the way the launcher lays one out. The names matter to the
# tests below: ``LAUNCH_ROOT`` is the launcher's own scratch — shared by every
# lane, and therefore denied whole — and everything the lane may touch is a more
# specific path inside it.
OPERATOR_HOME = "/Users/operator"
LAUNCH_ROOT = "/scratch"
LANE = "/scratch/lanes/001-lane"
LANE_SCRATCH = f"{LANE}/scratch"
LANE_TMP = f"{LANE}/scratch/tmp"
LANE_HOME = f"{LANE}/home"
LANE_RUNTIME = f"{LANE}/runtime/001-lane"
LANE_SHIM = f"{LANE_RUNTIME}/bin/claude-broker"
LANE_INPUT = f"{LANE}/input"
LANE_PACKET = f"{LANE_INPUT}/blockers.json"
LANE_SETTINGS = f"{LANE}/settings.json"
OTHER_LANE = "/scratch/lanes/002-other"
EMPTY_MCP = "/scratch/mcp-empty.json"
BROKER_HOME = "/scratch/broker/builder"
BROKER_PAYLOAD = "/scratch/cap-abcdef.json"
SOCKET = "/scratch/cap/lane.sock"
WORKTREE = "/work/tree"


def lane_document(**overrides: object) -> dict:
    """The document the launcher builds for one lane, with named overrides."""
    arguments: dict = {
        "worktree": WORKTREE,
        "lane_scratch": LANE_SCRATCH,
        "home": LANE_HOME,
        "runtime": LANE_RUNTIME,
        "lane_input": LANE_INPUT,
        "readable_files": (LANE_SETTINGS, EMPTY_MCP),
        "socket": SOCKET,
        "writable_worktree": False,
        "operator_home": OPERATOR_HOME,
        "denied_roots": (LAUNCH_ROOT,),
    }
    arguments.update(overrides)
    return document(**arguments)  # type: ignore[arg-type]


def dig(settings: dict, dotted: str) -> object:
    current: object = settings
    for part in dotted.split("."):
        if not isinstance(current, dict) or part not in current:
            return None
        current = current[part]
    return current


class PolicyDocumentTests(unittest.TestCase):
    """What the generated document says, before anything is written."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.tmp = Path(self._tmp.name)
        self.operator_home = OPERATOR_HOME
        self.socket = SOCKET
        self.document = lane_document()

    def test_the_sandbox_is_on_and_an_unavailable_one_is_fatal(self) -> None:
        self.assertIs(dig(self.document, "sandbox.enabled"), True)
        self.assertIs(dig(self.document, "sandbox.failIfUnavailable"), True)
        self.assertIs(dig(self.document, "sandbox.allowUnsandboxedCommands"), False)

    def test_there_is_no_escape_hatch(self) -> None:
        """No Apple Events, no excluded commands, no filesystem-disable, no extra dirs."""
        self.assertIs(dig(self.document, "sandbox.allowAppleEvents"), False)
        self.assertEqual(dig(self.document, "sandbox.excludedCommands"), [])
        self.assertIs(dig(self.document, "sandbox.filesystem.disabled"), False)
        self.assertEqual(dig(self.document, "permissions.additionalDirectories"), [])
        self.assertIs(dig(self.document, "enableAllProjectMcpServers"), False)
        self.assertEqual(dig(self.document, "enabledMcpjsonServers"), [])
        self.assertEqual(dig(self.document, "hooks"), {})

    def test_bash_network_defaults_are_closed(self) -> None:
        self.assertEqual(dig(self.document, "sandbox.network.allowedDomains"), [])
        self.assertEqual(dig(self.document, "sandbox.network.deniedDomains"), ["*"])
        self.assertIs(dig(self.document, "sandbox.network.allowLocalBinding"), False)

    def test_only_this_lanes_socket_is_reachable(self) -> None:
        self.assertEqual(
            dig(self.document, "sandbox.network.allowUnixSockets"), [self.socket]
        )

    def test_a_lane_with_no_channel_gets_no_socket(self) -> None:
        gate = lane_document(socket=None)
        self.assertEqual(dig(gate, "sandbox.network.allowUnixSockets"), [])

    def test_the_operator_home_and_its_credentials_are_denied(self) -> None:
        denied = dig(self.document, "sandbox.filesystem.denyRead")
        self.assertIn(self.operator_home, denied)
        for relative in (".ssh", ".gnupg", ".aws", ".config/gh", ".claude", ".netrc"):
            self.assertIn(f"{self.operator_home}/{relative}", denied)

    def test_the_only_root_inside_the_operator_home_is_the_lane_worktree(self) -> None:
        """A worktree may live under the operator's home; nothing else may."""
        for key in ("allowRead", "allowWrite"):
            for root in dig(self.document, f"sandbox.filesystem.{key}"):
                self.assertFalse(root.startswith(f"{self.operator_home}/"), root)
                self.assertNotEqual(root, self.operator_home)

    def test_reads_are_the_lane_worktree_its_own_material_and_trusted_runtimes(self) -> None:
        allowed = dig(self.document, "sandbox.filesystem.allowRead")
        for expected in (WORKTREE, LANE_SCRATCH, LANE_HOME, LANE_RUNTIME, LANE_INPUT):
            self.assertIn(expected, allowed)
        self.assertIn("/usr/lib", allowed)
        self.assertNotIn("/", allowed)
        # Never the launcher's shared scratch root, which holds every lane.
        self.assertNotIn(LAUNCH_ROOT, allowed)

    def test_writes_are_only_this_lanes_scratch_and_home(self) -> None:
        self.assertEqual(
            dig(self.document, "sandbox.filesystem.allowWrite"), [LANE_SCRATCH, LANE_HOME]
        )

    def test_a_reviewer_cannot_write_its_worktree_or_its_git_metadata(self) -> None:
        self.assertNotIn(WORKTREE, dig(self.document, "sandbox.filesystem.allowWrite"))
        self.assertIn(f"{WORKTREE}/.git", dig(self.document, "sandbox.filesystem.denyWrite"))

    def test_a_builder_may_write_its_worktree_but_never_its_git_metadata(self) -> None:
        builder = lane_document(writable_worktree=True)
        self.assertIn(WORKTREE, dig(builder, "sandbox.filesystem.allowWrite"))
        self.assertIn(f"{WORKTREE}/.git", dig(builder, "sandbox.filesystem.denyWrite"))
        self.assertTrue(decides(builder, WORKTREE, write=True))
        self.assertFalse(decides(builder, f"{WORKTREE}/.git", write=True))

    def test_every_tool_that_bypasses_the_bash_sandbox_is_denied(self) -> None:
        denied = dig(self.document, "permissions.deny")
        for tool in OUTSIDE_SANDBOX_TOOLS:
            self.assertIn(tool, denied)
        for tool in SANDBOXED_TOOLS:
            self.assertNotIn(tool, denied)

    def test_the_generated_document_passes_its_own_policy_check(self) -> None:
        assert_settings(
            self.document,
            source="memory",
            worktree=WORKTREE,
            socket=self.socket,
            operator_home=self.operator_home,
            writable_worktree=False,
            lane_writable=(LANE_SCRATCH, LANE_HOME),
            lane_readonly=(LANE_RUNTIME, LANE_INPUT, LANE_SETTINGS, EMPTY_MCP),
            denied_roots=(LAUNCH_ROOT,),
            foreign_paths=(OTHER_LANE, BROKER_HOME, BROKER_PAYLOAD),
        )


class WorktreeUnderTheOperatorHomeTests(unittest.TestCase):
    """Former-red (PAPI-90 item 1): a real checkout lives under the operator's home.

    ``~/projects/worktrees/<lane>`` is where a worktree actually is on the
    machine this runs on, and the previous policy refused *any* allowed root
    below the operator's home — so the production probe failed closed and no
    agent lane could launch at all. The home is still denied whole; exactly one
    path comes back inside it, and it is the worktree this lane was authorised
    for.
    """

    def setUp(self) -> None:
        self.home = "/Users/operator"
        self.worktree = "/Users/operator/projects/worktrees/lane"
        self.document = lane_document(worktree=self.worktree, operator_home=self.home)

    def test_the_operator_home_is_still_denied_for_reading(self) -> None:
        self.assertIn(self.home, dig(self.document, "sandbox.filesystem.denyRead"))

    def test_the_operator_home_is_never_denied_for_writing(self) -> None:
        """Former-red (live): a broad write denial takes the builder's worktree with it.

        ``~/projects/worktrees/<lane>`` is inside the operator's home, so a
        ``denyWrite`` on the home refused the builder its own checkout — the live
        probe reported ``Operation not permitted`` on all three of the writes that
        must succeed. The home stays denied for *reading*, where a nested
        allowance genuinely does reopen a path, and the credential directories
        carry their own exact write denials.
        """
        builder = lane_document(
            worktree=self.worktree, operator_home=self.home, writable_worktree=True
        )
        for settings in (self.document, builder):
            self.assertNotIn(self.home, dig(settings, "sandbox.filesystem.denyWrite"))
        self.assertTrue(decides(builder, self.worktree, write=True))
        self.assertTrue(decides(builder, LANE_SCRATCH, write=True))
        self.assertTrue(decides(builder, LANE_HOME, write=True))

    def test_each_credential_directory_carries_its_own_write_denial(self) -> None:
        denied = dig(self.document, "sandbox.filesystem.denyWrite")
        for relative in CREDENTIAL_HOME_SUBPATHS:
            self.assertIn(f"{self.home}/{relative}", denied)

    def test_a_real_worktree_under_the_operator_home_is_accepted(self) -> None:
        """The regression: this used to raise, and no lane could start."""
        assert_settings(
            self.document,
            source="memory",
            worktree=self.worktree,
            socket=SOCKET,
            operator_home=self.home,
            writable_worktree=False,
        )
        self.assertTrue(decides(self.document, self.worktree, write=False))
        self.assertTrue(decides(self.document, f"{self.worktree}/src/app.py", write=False))

    def test_a_builder_worktree_under_the_operator_home_stays_writable(self) -> None:
        builder = lane_document(
            worktree=self.worktree, operator_home=self.home, writable_worktree=True
        )
        assert_settings(
            builder,
            source="memory",
            worktree=self.worktree,
            socket=SOCKET,
            operator_home=self.home,
            writable_worktree=True,
        )
        self.assertTrue(decides(builder, f"{self.worktree}/src/app.py", write=True))

    def test_every_credential_directory_in_that_home_stays_denied(self) -> None:
        for relative in CREDENTIAL_HOME_SUBPATHS:
            path = f"{self.home}/{relative}"
            with self.subTest(path=path):
                self.assertFalse(decides(self.document, path, write=False))
                self.assertFalse(decides(self.document, path, write=True))
        for path in (
            f"{self.home}/.ssh/id_ed25519",
            f"{self.home}/Library/Keychains/login.keychain-db",
            f"{self.home}/.config/gh/hosts.yml",
        ):
            with self.subTest(path=path):
                self.assertFalse(decides(self.document, path, write=False))

    def test_an_unrelated_subpath_of_that_home_stays_denied(self) -> None:
        """Neighbouring directories are not reachable just because a sibling is."""
        for path in (
            self.home,
            f"{self.home}/Documents",
            f"{self.home}/projects",
            f"{self.home}/projects/worktrees",
            f"{self.home}/projects/worktrees/other-lane",
            f"{self.home}/projects/worktrees/lane-two",
        ):
            with self.subTest(path=path):
                self.assertFalse(decides(self.document, path, write=False))
                self.assertFalse(decides(self.document, path, write=True))

    def test_allowing_an_unrelated_home_subpath_is_still_refused(self) -> None:
        """Widening back to "anything under the home" fails validation."""
        loosened = json.loads(json.dumps(self.document))
        loosened["sandbox"]["filesystem"]["allowRead"].append(f"{self.home}/Documents")
        with self.assertRaises(LaunchPolicyError) as caught:
            assert_settings(
                loosened,
                source="memory",
                worktree=self.worktree,
                operator_home=self.home,
            )
        self.assertIn("operator's home", caught.exception.message)
        self.assertEqual(caught.exception.evidence["root"], f"{self.home}/Documents")

    def test_allowing_a_credential_directory_is_refused_even_as_the_worktree(self) -> None:
        """A lane cannot be authorised for ``~/.ssh`` by calling it a worktree."""
        credential = f"{self.home}/.ssh"
        loosened = lane_document(worktree=credential, operator_home=self.home)
        with self.assertRaises(LaunchPolicyError) as caught:
            assert_settings(
                loosened, source="memory", worktree=credential, operator_home=self.home
            )
        self.assertIn("credential directory", caught.exception.message)


class LaneScopedMaterialTests(unittest.TestCase):
    """Former-red (PAPI-90 item 2): the launcher's scratch root is not a lane's.

    The document used to allow the whole :class:`~.launchers.LaunchBroker`
    scratch for read *and* write. That root holds every lane's runtime, every
    lane's synthetic home, every lane's settings file, the empty MCP config, and
    the capability broker's own request payloads — so a surviving descendant of
    lane A could rewrite the shim, the policy, or the home that lane B would
    later be launched with. Mode bits are not the answer: those files are owned
    by the same user the lane runs as, and that user can put a write bit back.

    So the root is denied and the lane's own two directories are allowed back
    inside it. Every assertion below is about a concrete path.
    """

    def setUp(self) -> None:
        self.document = lane_document()
        self.builder = lane_document(writable_worktree=True)

    def denied(self, path: str, *, document: dict | None = None) -> None:
        settings = self.document if document is None else document
        self.assertFalse(decides(settings, path, write=False), f"readable: {path}")
        self.assertFalse(decides(settings, path, write=True), f"writable: {path}")

    def readable_not_writable(self, path: str) -> None:
        self.assertTrue(decides(self.document, path, write=False), f"unreadable: {path}")
        self.assertFalse(decides(self.document, path, write=True), f"writable: {path}")

    def test_the_launcher_scratch_root_is_denied_for_reading(self) -> None:
        self.assertIn(LAUNCH_ROOT, dig(self.document, "sandbox.filesystem.denyRead"))
        self.denied(LAUNCH_ROOT)
        self.denied("/scratch/lanes")

    def test_the_launcher_scratch_root_is_never_denied_for_writing(self) -> None:
        """Former-red (live): a broad write denial takes the lane's own roots with it.

        This lane's scratch and synthetic home are *inside* the launcher's
        scratch root. A ``denyWrite`` on the root is absolute in this client, so
        naming it there denied the lane the two directories it exists to write —
        which is exactly what the live probe reported. Sibling lanes stay
        unwritable for a different reason: none of them is the working directory
        and none is an ``allowWrite`` root.
        """
        self.assertNotIn(LAUNCH_ROOT, dig(self.document, "sandbox.filesystem.denyWrite"))
        self.assertTrue(decides(self.document, LANE_SCRATCH, write=True))
        self.assertTrue(decides(self.document, LANE_HOME, write=True))
        self.assertFalse(decides(self.document, LAUNCH_ROOT, write=True))
        self.assertFalse(decides(self.document, OTHER_LANE, write=True))

    def test_the_lane_owns_its_scratch_and_home_and_nothing_wider(self) -> None:
        for path in (LANE_SCRATCH, LANE_TMP, LANE_HOME, f"{LANE_HOME}/.cache/thing"):
            with self.subTest(path=path):
                self.assertTrue(decides(self.document, path, write=False))
                self.assertTrue(decides(self.document, path, write=True))

    def test_the_lane_cannot_write_its_own_runtime_or_shim(self) -> None:
        """The shim the lane runs is readable, and replaceable by nobody."""
        self.readable_not_writable(LANE_RUNTIME)
        self.readable_not_writable(LANE_SHIM)

    def test_the_lane_cannot_write_its_own_settings_file(self) -> None:
        self.readable_not_writable(LANE_SETTINGS)

    def test_the_lane_cannot_write_its_own_frozen_input(self) -> None:
        self.readable_not_writable(LANE_INPUT)
        self.readable_not_writable(LANE_PACKET)

    def test_the_lane_cannot_write_the_empty_mcp_config(self) -> None:
        self.readable_not_writable(EMPTY_MCP)

    def test_the_brokers_own_material_is_out_of_reach(self) -> None:
        """The broker acts with a real credential; no lane reads where it works."""
        self.denied(BROKER_HOME)
        self.denied(f"{BROKER_HOME}/.config/gh/hosts.yml")
        self.denied(BROKER_PAYLOAD)

    def test_another_lane_is_out_of_reach_entirely(self) -> None:
        for path in (
            OTHER_LANE,
            f"{OTHER_LANE}/home",
            f"{OTHER_LANE}/home/.gitconfig",
            f"{OTHER_LANE}/scratch",
            f"{OTHER_LANE}/scratch/tmp/work",
            f"{OTHER_LANE}/runtime/002-other/bin/claude-broker",
            f"{OTHER_LANE}/settings.json",
            f"{OTHER_LANE}/input/blockers.json",
        ):
            with self.subTest(path=path):
                self.denied(path)

    def test_an_os_temp_path_is_not_a_way_back_in(self) -> None:
        """The same layout under a real OS temp root behaves the same way."""
        root = "/var/folders/xx/T/pr-prover-launch-abc"
        lane = f"{root}/lanes/001-lane"
        settings = document(
            worktree=WORKTREE,
            lane_scratch=f"{lane}/scratch",
            home=f"{lane}/home",
            runtime=f"{lane}/runtime/001-lane",
            lane_input=f"{lane}/input",
            readable_files=(f"{lane}/settings.json", f"{root}/mcp-empty.json"),
            socket=SOCKET,
            writable_worktree=True,
            operator_home=OPERATOR_HOME,
            denied_roots=(root, "/var/folders/xx/T/pr-prover-scratch"),
        )
        self.assertTrue(decides(settings, f"{lane}/scratch/tmp/x", write=True))
        for path in (
            root,
            f"{root}/mcp-empty.json",
            f"{root}/lanes/002-other/home",
            f"{lane}/runtime/001-lane/bin/claude-broker",
            f"{lane}/settings.json",
            "/var/folders/xx/T/pr-prover-scratch/pr-prover-7-xyz/blockers-attempt1.json",
        ):
            with self.subTest(path=path):
                self.assertFalse(decides(settings, path, write=True), path)

    def test_the_builder_worktree_is_still_usable(self) -> None:
        """Denying everything shared must not cost the lane the work it came to do."""
        self.assertTrue(decides(self.builder, WORKTREE, write=False))
        self.assertTrue(decides(self.builder, f"{WORKTREE}/src/app.py", write=True))
        self.assertTrue(decides(self.builder, f"{LANE}/scratch/tmp/build.log", write=True))

    def test_validation_refuses_a_document_that_shares_the_scratch_root_again(self) -> None:
        """Former-red: the exact shape this repair removed no longer validates."""
        shared = document(
            worktree=WORKTREE,
            lane_scratch=LAUNCH_ROOT,
            home=LANE_HOME,
            runtime=LANE_RUNTIME,
            lane_input=LANE_INPUT,
            readable_files=(LANE_SETTINGS, EMPTY_MCP),
            socket=SOCKET,
            writable_worktree=False,
            operator_home=OPERATOR_HOME,
            denied_roots=(),
        )
        self.assertTrue(decides(shared, OTHER_LANE, write=True))
        with self.assertRaises(LaunchPolicyError) as caught:
            assert_settings(
                shared,
                source="memory",
                worktree=WORKTREE,
                socket=SOCKET,
                operator_home=OPERATOR_HOME,
                writable_worktree=False,
                denied_roots=(LAUNCH_ROOT,),
                foreign_paths=(OTHER_LANE, EMPTY_MCP),
            )
        self.assertIn("scratch root", caught.exception.message)

    def test_naming_a_read_only_root_in_allow_write_is_refused_as_contradictory(self) -> None:
        """A write denial outranks any allowance, so naming both is a bug, not a policy."""
        for root in (LANE_RUNTIME, LANE_SETTINGS, LANE_INPUT):
            loosened = json.loads(json.dumps(self.document))
            loosened["sandbox"]["filesystem"]["allowWrite"].append(root)
            with self.subTest(root=root):
                # The allowance buys nothing: the denial is absolute.
                self.assertFalse(decides(loosened, root, write=True))
                with self.assertRaises(LaunchPolicyError) as caught:
                    assert_settings(loosened, source="memory")
                self.assertEqual(caught.exception.evidence["allowWrite"], root)

    def test_validation_refuses_a_writable_runtime_or_settings_file(self) -> None:
        for root in (LANE_RUNTIME, LANE_SETTINGS, LANE_INPUT):
            loosened = json.loads(json.dumps(self.document))
            loosened["sandbox"]["filesystem"]["allowWrite"].append(root)
            loosened["sandbox"]["filesystem"]["denyWrite"] = [
                entry
                for entry in loosened["sandbox"]["filesystem"]["denyWrite"]
                if entry != root
            ]
            with self.subTest(root=root), self.assertRaises(LaunchPolicyError) as caught:
                assert_settings(
                    loosened,
                    source="memory",
                    lane_readonly=(LANE_RUNTIME, LANE_SETTINGS, LANE_INPUT),
                )
            self.assertIn("mode bits do not keep", caught.exception.message)

    def test_validation_refuses_a_document_that_reaches_a_sibling_lane(self) -> None:
        loosened = json.loads(json.dumps(self.document))
        loosened["sandbox"]["filesystem"]["allowRead"].append(OTHER_LANE)
        with self.assertRaises(LaunchPolicyError) as caught:
            assert_settings(loosened, source="memory", foreign_paths=(OTHER_LANE,))
        self.assertIn("not this lane's", caught.exception.message)

    def test_validation_refuses_a_lane_that_cannot_reach_its_own_scratch(self) -> None:
        loosened = json.loads(json.dumps(self.document))
        loosened["sandbox"]["filesystem"]["allowWrite"] = [LANE_HOME]
        with self.assertRaises(LaunchPolicyError):
            assert_settings(
                loosened, source="memory", lane_writable=(LANE_SCRATCH, LANE_HOME)
            )


class WriteBoundaryTests(unittest.TestCase):
    """Former-red (live probe, Claude Code 2.1.219): writes do not nest.

    Hermes generated this exact policy for a disposable builder worktree under
    ``/Users/creator/projects/worktrees``, handed it to a real client through
    ``--settings`` with ``--setting-sources ''``, strict MCP, Bash only, and
    ``allowUnsandboxedCommands=false``, and ran a live shell in it. Every denial
    held. So did three that must not: the builder's own worktree, the lane's own
    scratch, and the lane's own synthetic home were all refused with
    ``Operation not permitted``, because both were inside a region this document
    had broadly denied for writing and a nested ``allowWrite`` does not reopen
    one.

    Reads are not like that — a broad ``denyRead`` plus a specific ``allowRead``
    is documented and was confirmed live — so the two are modelled separately
    here and everywhere else.
    """

    def setUp(self) -> None:
        self.home = "/Users/operator"
        self.worktree = "/Users/operator/projects/worktrees/lane"
        self.builder = lane_document(
            worktree=self.worktree, operator_home=self.home, writable_worktree=True
        )

    def test_the_three_writes_the_live_probe_lost_are_allowed(self) -> None:
        for path in (
            self.worktree,
            f"{self.worktree}/src/app.py",
            LANE_SCRATCH,
            f"{LANE_SCRATCH}/tmp/build.log",
            LANE_HOME,
            f"{LANE_HOME}/.cache/thing",
        ):
            with self.subTest(path=path):
                self.assertTrue(decides(self.builder, path, write=True), path)

    def test_no_write_denial_covers_any_path_the_lane_must_write(self) -> None:
        """The invariant, stated directly against the generated document."""
        filesystem = dig(self.builder, "sandbox.filesystem")
        for allowed in filesystem["allowWrite"]:
            for denied in filesystem["denyWrite"]:
                with self.subTest(allow=allowed, deny=denied):
                    self.assertFalse(
                        allowed == denied or allowed.startswith(f"{denied}/"),
                        f"{denied} covers {allowed}",
                    )

    def test_a_broad_write_denial_on_the_operator_home_is_refused(self) -> None:
        loosened = json.loads(json.dumps(self.builder))
        loosened["sandbox"]["filesystem"]["denyWrite"].append(self.home)
        self.assertFalse(decides(loosened, self.worktree, write=True))
        with self.assertRaises(LaunchPolicyError) as caught:
            assert_settings(
                loosened,
                source="memory",
                worktree=self.worktree,
                operator_home=self.home,
                writable_worktree=True,
            )
        self.assertIn("operator's whole home", caught.exception.message)

    def test_a_broad_write_denial_on_the_launcher_scratch_is_refused(self) -> None:
        loosened = json.loads(json.dumps(self.builder))
        loosened["sandbox"]["filesystem"]["denyWrite"].append(LAUNCH_ROOT)
        self.assertFalse(decides(loosened, LANE_SCRATCH, write=True))
        self.assertFalse(decides(loosened, LANE_HOME, write=True))
        with self.assertRaises(LaunchPolicyError) as caught:
            assert_settings(loosened, source="memory", denied_roots=(LAUNCH_ROOT,))
        self.assertIn("whole scratch root", caught.exception.message)

    def test_building_such_a_document_fails_where_it_is_built(self) -> None:
        """Not only at validation: a policy that denies its own writes never exists."""
        with self.assertRaises(LaunchPolicyError) as caught:
            document(
                worktree=self.worktree,
                lane_scratch=LANE_SCRATCH,
                home=LANE_HOME,
                runtime=LANE_SCRATCH,  # the lane's runtime inside its own writable root
                lane_input=LANE_INPUT,
                readable_files=(LANE_SETTINGS, EMPTY_MCP),
                socket=SOCKET,
                writable_worktree=True,
                operator_home=self.home,
                denied_roots=(LAUNCH_ROOT,),
            )
        self.assertIn("must write", caught.exception.message)

    def test_the_exact_immutable_denials_still_win(self) -> None:
        """A denial that shadows nothing the lane needs is still absolute."""
        for path in (
            f"{self.worktree}/.git",
            f"{self.worktree}/.git/config",
            LANE_RUNTIME,
            LANE_SHIM,
            LANE_INPUT,
            LANE_PACKET,
            LANE_SETTINGS,
            EMPTY_MCP,
            f"{self.home}/.ssh",
            f"{self.home}/.ssh/id_ed25519",
            f"{self.home}/Library/Keychains/login.keychain-db",
        ):
            with self.subTest(path=path):
                self.assertFalse(decides(self.builder, path, write=True), path)

    def test_everything_outside_the_lane_is_unwritable_without_a_denial(self) -> None:
        """No broad denial is needed, and none is used: absence of an allowance is enough."""
        denied = dig(self.builder, "sandbox.filesystem.denyWrite")
        for path in (
            OTHER_LANE,
            f"{OTHER_LANE}/home/.gitconfig",
            f"{OTHER_LANE}/scratch/tmp/work",
            BROKER_HOME,
            BROKER_PAYLOAD,
            LAUNCH_ROOT,
            f"{self.home}/Documents",
            "/usr/local/bin",
        ):
            with self.subTest(path=path):
                self.assertFalse(decides(self.builder, path, write=True), path)
                self.assertNotIn(path, denied)

    def test_a_reviewer_worktree_is_denied_by_exact_path_not_by_omission(self) -> None:
        """The worktree is the working directory, which this client makes writable."""
        reviewer = lane_document(
            worktree=self.worktree, operator_home=self.home, writable_worktree=False
        )
        self.assertIn(self.worktree, dig(reviewer, "sandbox.filesystem.denyWrite"))
        self.assertFalse(decides(reviewer, f"{self.worktree}/src/app.py", write=True))
        self.assertTrue(decides(reviewer, f"{self.worktree}/src/app.py", write=False))
        # And denying it costs the reviewer neither of its own writable roots.
        self.assertTrue(decides(reviewer, LANE_SCRATCH, write=True))
        self.assertTrue(decides(reviewer, LANE_HOME, write=True))

    def test_reads_still_nest_the_way_the_client_documents(self) -> None:
        """The asymmetry, asserted as an asymmetry rather than assumed."""
        self.assertIn(self.home, dig(self.builder, "sandbox.filesystem.denyRead"))
        self.assertIn(LAUNCH_ROOT, dig(self.builder, "sandbox.filesystem.denyRead"))
        self.assertTrue(decides(self.builder, self.worktree, write=False))
        self.assertTrue(decides(self.builder, LANE_SCRATCH, write=False))
        self.assertFalse(decides(self.builder, f"{self.home}/Documents", write=False))
        self.assertFalse(decides(self.builder, OTHER_LANE, write=False))


class DocumentedSettingsKeyTests(unittest.TestCase):
    """Former-red (PAPI-90 item 3): only keys this client actually reads.

    ``sandbox.filesystem.enabled``, ``sandbox.network.allowAll``,
    ``sandbox.network.allowedHosts``, and a root-level
    ``sandbox.allowLocalBinding`` all read as strict and are all ignored by
    Claude Code 2.1.219. A document that carried them described a policy nobody
    enforced, so they are gone and a document that reintroduces one is refused.
    """

    def setUp(self) -> None:
        self.document = lane_document()

    def test_the_document_carries_only_documented_sandbox_keys(self) -> None:
        self.assertEqual(set(self.document["sandbox"]), set(KNOWN_SANDBOX_KEYS))
        self.assertEqual(
            set(self.document["sandbox"]["network"]), set(KNOWN_NETWORK_KEYS)
        )
        self.assertEqual(
            set(self.document["sandbox"]["filesystem"]), set(KNOWN_FILESYSTEM_KEYS)
        )

    def test_no_ignored_key_survives_in_the_document(self) -> None:
        for dotted in IGNORED_SANDBOX_KEYS:
            with self.subTest(key=dotted):
                self.assertIsNone(dig(self.document, dotted))

    def test_reintroducing_an_ignored_key_fails_closed(self) -> None:
        for dotted, value in (
            ("sandbox.allowLocalBinding", False),
            ("sandbox.filesystem.enabled", True),
            ("sandbox.network.allowAll", False),
            ("sandbox.network.allowedHosts", []),
        ):
            loosened = json.loads(json.dumps(self.document))
            parts = dotted.split(".")
            target = loosened
            for part in parts[:-1]:
                target = target[part]
            target[parts[-1]] = value
            with self.subTest(key=dotted), self.assertRaises(LaunchPolicyError) as caught:
                assert_settings(loosened, source="memory")
            self.assertEqual(caught.exception.evidence["key"], dotted)

    def test_an_undocumented_sandbox_key_fails_closed(self) -> None:
        for section, key in (
            ("sandbox", "allowEverything"),
            ("network", "allowAllHosts"),
            ("filesystem", "allowAllPaths"),
        ):
            loosened = json.loads(json.dumps(self.document))
            target = loosened["sandbox"] if section == "sandbox" else loosened["sandbox"][section]
            target[key] = True
            with self.subTest(key=key), self.assertRaises(LaunchPolicyError) as caught:
                assert_settings(loosened, source="memory")
            self.assertIn(key, caught.exception.evidence["unknown"])

    def test_each_effective_key_is_checked_by_the_name_the_client_reads(self) -> None:
        """Every required key resolves in the document under its documented path."""
        for dotted, expected in REQUIRED:
            with self.subTest(key=dotted):
                self.assertEqual(dig(self.document, dotted), expected)

    def test_the_network_is_closed_by_a_key_that_is_read(self) -> None:
        """An empty allow list is not a denial on its own; ``*`` denied is."""
        self.assertEqual(dig(self.document, "sandbox.network.deniedDomains"), ["*"])
        loosened = json.loads(json.dumps(self.document))
        loosened["sandbox"]["network"]["deniedDomains"] = []
        with self.assertRaises(LaunchPolicyError) as caught:
            assert_settings(loosened, source="memory")
        self.assertEqual(caught.exception.evidence["key"], "sandbox.network.deniedDomains")


class PolicyRefusalTests(unittest.TestCase):
    """Former-red: every loosening of the document fails closed."""

    def setUp(self) -> None:
        self.document = lane_document()

    def loosened(self, dotted: str, value: object) -> dict:
        copy = json.loads(json.dumps(self.document))
        parts = dotted.split(".")
        target = copy
        for part in parts[:-1]:
            target = target[part]
        target[parts[-1]] = value
        return copy

    def refuses(self, settings: dict, **checks: object) -> LaunchPolicyError:
        with self.assertRaises(LaunchPolicyError) as caught:
            assert_settings(settings, source="memory", **checks)  # type: ignore[arg-type]
        self.assertEqual(caught.exception.reason, "launch-policy")
        return caught.exception

    def test_every_required_setting_is_actually_required(self) -> None:
        for dotted, expected in REQUIRED:
            loosened = True if expected is False else (False if expected is True else "loosened")
            with self.subTest(setting=dotted):
                self.refuses(self.loosened(dotted, loosened))

    def test_a_missing_sandbox_section_fails_closed(self) -> None:
        self.refuses({"permissions": {"deny": list(OUTSIDE_SANDBOX_TOOLS)}})
        self.refuses({})

    def test_a_document_that_is_not_an_object_fails_closed(self) -> None:
        self.refuses([])  # type: ignore[arg-type]

    def test_leaving_a_file_tool_available_fails_closed(self) -> None:
        for tool in OUTSIDE_SANDBOX_TOOLS:
            remaining = [name for name in OUTSIDE_SANDBOX_TOOLS if name != tool]
            with self.subTest(tool=tool):
                error = self.refuses(self.loosened("permissions.deny", remaining))
                self.assertIn(tool, error.evidence["missing"])

    def test_allowing_the_whole_filesystem_fails_closed(self) -> None:
        for root in ("/", "*", "**", ""):
            with self.subTest(root=root):
                self.refuses(self.loosened("sandbox.filesystem.allowRead", [root]))
                self.refuses(self.loosened("sandbox.filesystem.allowWrite", [root]))

    def test_allowing_a_second_unix_socket_fails_closed(self) -> None:
        self.refuses(
            self.loosened(
                "sandbox.network.allowUnixSockets",
                [SOCKET, "/scratch/cap/other.sock"],
            )
        )

    def test_allowing_another_lanes_socket_fails_closed(self) -> None:
        error = self.refuses(
            self.loosened("sandbox.network.allowUnixSockets", ["/scratch/cap/other.sock"]),
            socket=SOCKET,
        )
        self.assertIn("exactly this lane's capability", error.message)

    def test_a_lane_with_no_channel_given_a_socket_fails_closed(self) -> None:
        self.refuses(self.document, socket=None)

    def test_allowing_a_path_inside_the_operator_home_fails_closed(self) -> None:
        error = self.refuses(
            self.loosened(
                "sandbox.filesystem.allowRead",
                [WORKTREE, f"{OPERATOR_HOME}/.ssh"],
            ),
            operator_home=OPERATOR_HOME,
        )
        self.assertIn("operator's home", error.message)

    def test_dropping_the_home_denial_fails_closed(self) -> None:
        self.refuses(
            self.loosened("sandbox.filesystem.denyRead", []),
            operator_home=OPERATOR_HOME,
        )

    def test_a_reviewer_worktree_that_became_writable_fails_closed(self) -> None:
        loosened = self.loosened("sandbox.filesystem.allowWrite", [LANE_SCRATCH, WORKTREE])
        loosened["sandbox"]["filesystem"]["denyWrite"] = [
            entry
            for entry in loosened["sandbox"]["filesystem"]["denyWrite"]
            if entry != WORKTREE
        ]
        error = self.refuses(loosened, worktree=WORKTREE, writable_worktree=False)
        self.assertIn("whether the worktree is writable", error.message)

    def test_a_reviewer_worktree_left_merely_unallowed_fails_closed(self) -> None:
        """Silence is not a denial: the worktree is the lane's working directory."""
        loosened = self.loosened("sandbox.filesystem.denyWrite", [f"{WORKTREE}/.git"])
        error = self.refuses(loosened, worktree=WORKTREE, writable_worktree=False)
        self.assertIn("say nothing about writing to the worktree", error.message)

    def test_dropping_the_git_metadata_denial_fails_closed(self) -> None:
        self.refuses(
            self.loosened("sandbox.filesystem.denyWrite", []), worktree=WORKTREE
        )

    def test_denying_the_worktree_the_lane_was_launched_in_fails_closed(self) -> None:
        """A worktree named in allowRead but shadowed by a longer denial is not usable."""
        loosened = self.loosened(
            "sandbox.filesystem.denyRead",
            [*dig(self.document, "sandbox.filesystem.denyRead"), f"{WORKTREE}/"],
        )
        error = self.refuses(loosened, worktree=WORKTREE)
        self.assertIn("deny the worktree", error.message)


class SettingsFileTests(unittest.TestCase):
    """The file on disk, and what happens when something changes it."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.tmp = Path(self._tmp.name)
        self.document = lane_document()

    def test_a_written_settings_file_is_owner_only(self) -> None:
        path = write(self.tmp / "lane.settings.json", self.document)
        self.assertEqual(path.stat().st_mode & 0o077, 0)
        self.assertEqual(json.loads(path.read_text(encoding="utf-8")), self.document)

    def test_writing_over_an_existing_settings_file_fails_closed(self) -> None:
        path = self.tmp / "lane.settings.json"
        path.write_text("{}", encoding="utf-8")
        with self.assertRaises(LaunchPolicyError) as caught:
            write(path, self.document)
        self.assertIn("already exists", caught.exception.message)

    def test_a_settings_file_edited_after_it_was_written_fails_closed(self) -> None:
        """Former-red: the document is proved from disk, not from memory."""
        path = write(self.tmp / "lane.settings.json", self.document)
        loosened = json.loads(path.read_text(encoding="utf-8"))
        loosened["sandbox"]["allowUnsandboxedCommands"] = True
        path.write_text(json.dumps(loosened), encoding="utf-8")
        with self.assertRaises(LaunchPolicyError) as caught:
            read_and_assert(path)
        self.assertEqual(caught.exception.evidence["key"], "sandbox.allowUnsandboxedCommands")

    def test_an_unreadable_settings_file_fails_closed(self) -> None:
        with self.assertRaises(LaunchPolicyError):
            read_and_assert(self.tmp / "absent.json")

    def test_a_settings_file_that_is_not_json_fails_closed(self) -> None:
        path = self.tmp / "broken.json"
        path.write_text("not json", encoding="utf-8")
        with self.assertRaises(LaunchPolicyError):
            read_and_assert(path)


class RecordingRunner:
    def __init__(self) -> None:
        self.calls: list[dict] = []

    def run(self, argv, *, cwd=None, env=None, timeout=None):  # type: ignore[no-untyped-def]
        self.calls.append({"argv": tuple(argv), "env": dict(env or {}), "cwd": cwd})
        return CommandResult(argv=tuple(argv), returncode=0, stdout="done\n", stderr="")

    @property
    def last(self) -> dict:
        return self.calls[-1]


class LaunchedSandboxTests(unittest.TestCase):
    """What an actual agent launch carries."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.tmp = Path(self._tmp.name)
        self.config = make_config(self.tmp, source_repo=make_source_repo(self.tmp))
        self.worktree = self.config.worktree_root / "attempt1"
        self.worktree.mkdir(parents=True)
        self.runner = RecordingRunner()
        self.lane_bin = lane_bin(self.tmp)
        self.operator_home = self.tmp / "operator-home"
        self.operator_home.mkdir()
        self.blockers = self.tmp / "blockers.json"
        self.blockers.write_text('{"blockers": []}\n', encoding="utf-8")
        self.broker = make_broker(
            self.config,
            self.runner,
            scratch_root=self.tmp,
            env=parent_env(
                HOME=str(self.operator_home), PATH=f"{self.lane_bin}:/usr/bin:/bin"
            ),
        )
        self.addCleanup(self.broker.close)

    def launch_reviewer(self) -> tuple[str, ...]:
        self.broker.run_reviewer(
            role="A", identity="reviewer", agent=AGENT, argv=None,
            bound=BOUND, cwd=self.worktree, timeout=None,
        )
        return self.runner.last["argv"]

    def launch_builder(self) -> tuple[str, ...]:
        self.broker.run_builder(
            identity="builder", agent=AGENT, argv=None, bound=BOUND,
            cwd=self.worktree, timeout=None, attempt=1, mode="initial",
            blockers_file=self.blockers,
            signature="Fixed by: a signature long enough",
        )
        return self.runner.last["argv"]

    def settings_of(self, argv: tuple[str, ...]) -> dict:
        return json.loads(
            Path(argv[argv.index("--settings") + 1]).read_text(encoding="utf-8")
        )

    def test_an_agent_lane_carries_a_launcher_owned_settings_file(self) -> None:
        argv = self.launch_reviewer()
        self.assertIn("--settings", argv)
        path = Path(argv[argv.index("--settings") + 1])
        self.assertTrue(path.is_absolute())
        assert_settings(self.settings_of(argv), source=str(path))

    def test_an_agent_lane_reads_no_settings_source_at_all(self) -> None:
        """Neither the operator's settings nor a .claude directory the PR added."""
        self.assertIn(SETTING_SOURCES_ENTRY, self.launch_reviewer())

    def test_the_settings_allow_exactly_this_lanes_capability_socket(self) -> None:
        argv = self.launch_reviewer()
        sockets = dig(self.settings_of(argv), "sandbox.network.allowUnixSockets")
        self.assertEqual(len(sockets), 1)
        self.assertEqual(sockets[0], self.runner.last["env"]["PR_PROVER_CAPABILITY_SOCKET"])

    def test_the_settings_deny_the_operator_home_of_this_run(self) -> None:
        argv = self.launch_reviewer()
        denied = dig(self.settings_of(argv), "sandbox.filesystem.denyRead")
        self.assertIn(str(self.operator_home), denied)

    def test_a_reviewer_worktree_is_read_only_and_a_builders_is_not(self) -> None:
        reviewer = self.settings_of(self.launch_reviewer())
        builder = self.settings_of(self.launch_builder())
        tree = str(self.worktree)
        self.assertNotIn(tree, dig(reviewer, "sandbox.filesystem.allowWrite"))
        self.assertIn(tree, dig(reviewer, "sandbox.filesystem.allowRead"))
        self.assertIn(tree, dig(builder, "sandbox.filesystem.allowWrite"))
        for settings in (reviewer, builder):
            self.assertIn(f"{tree}/.git", dig(settings, "sandbox.filesystem.denyWrite"))

    def test_every_launch_gets_a_fresh_settings_file(self) -> None:
        first = self.launch_reviewer()
        second = self.launch_builder()
        self.assertNotEqual(
            first[first.index("--settings") + 1], second[second.index("--settings") + 1]
        )

    def test_the_lane_environment_scrubs_its_subprocesses(self) -> None:
        """A lane's own shells must not re-export its capability secret."""
        self.launch_reviewer()
        env = self.runner.last["env"]
        self.assertEqual(env[SUBPROCESS_ENV_SCRUB], ENV_SCRUB_VALUE)
        self.assertIn(CAPABILITY_SECRET, env)


class ArgvOwnershipTests(unittest.TestCase):
    """Former-red: a caller cannot supply, replace, or duplicate either flag."""

    def test_a_caller_supplied_settings_flag_is_refused(self) -> None:
        for argv in (
            ["./lane.sh", "--settings", "/tmp/theirs.json"],
            ["./lane.sh", "--settings=/tmp/theirs.json"],
            ["./lane.sh", "--setting-sources", "user"],
            ["./lane.sh", SETTING_SOURCES_ENTRY],
            ["./lane.sh", "--setting-sources=user,project"],
        ):
            with self.subTest(argv=argv), self.assertRaises(LaunchPolicyError) as caught:
                assert_launchable(argv)
            self.assertEqual(caught.exception.reason, "launch-policy")

    def test_only_the_exact_launcher_owned_settings_path_is_accepted(self) -> None:
        ours = "/scratch/runtime/001-lane.settings.json"
        assert_launchable(
            ["claude", "--settings", ours, SETTING_SOURCES_ENTRY],
            settings=ours,
            setting_sources=True,
        )
        with self.assertRaises(LaunchPolicyError):
            assert_launchable(
                ["claude", "--settings", "/tmp/theirs.json", SETTING_SOURCES_ENTRY],
                settings=ours,
                setting_sources=True,
            )

    def test_a_second_settings_entry_is_refused(self) -> None:
        """A later occurrence a parser might prefer is not a way in."""
        ours = "/scratch/runtime/001-lane.settings.json"
        with self.assertRaises(LaunchPolicyError) as caught:
            assert_launchable(
                ["claude", "--settings", ours, "--settings", ours, SETTING_SOURCES_ENTRY],
                settings=ours,
                setting_sources=True,
            )
        self.assertIn("exactly one", caught.exception.message)

    def test_a_missing_settings_entry_is_refused(self) -> None:
        ours = "/scratch/runtime/001-lane.settings.json"
        with self.assertRaises(LaunchPolicyError):
            assert_launchable(["claude", SETTING_SOURCES_ENTRY], settings=ours, setting_sources=True)
        with self.assertRaises(LaunchPolicyError):
            assert_launchable(["claude", "--settings", ours], settings=ours, setting_sources=True)

    def test_both_flags_are_still_on_the_forbidden_list(self) -> None:
        self.assertIn("--settings", FORBIDDEN_FLAGS)
        self.assertIn("--setting-sources", FORBIDDEN_FLAGS)


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
